package com.example.simulation

import com.example.model.*
import kotlin.random.Random

object ArenaDatabase {

    fun createInitialPersistentFighters(): MutableList<PersistentFighter> {
        return mutableListOf(
            // --- LOCAL PIT ---
            PersistentFighter(
                id = "fighter_pit_champ",
                name = "Tullius",
                nickname = "Bone Breaker",
                age = 25,
                origin = Origin.GAUL,
                ethnicity = "Celtic Gaul",
                gladiatorClass = GladiatorClass.MURMILLO,
                ludusAffiliation = "Subura Pit Guild",
                ownerName = "Lanista Varo",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.AGGRESSOR,
                signatureTactic = "Battering Shield Smash",
                equipmentSummary = "Reinforced wooden scutum & notched iron gladius",
                strength = 16,
                speed = 11,
                agility = 10,
                endurance = 14,
                reflex = 12,
                painTolerance = 17,
                swordsmanship = 13,
                shieldSkill = 14,
                discipline = 11,
                wins = 8,
                losses = 2,
                kills = 4,
                spared = 1,
                currentWinStreak = 3,
                prestige = 650,
                crowdApproval = 68,
                denariiEarned = 1400,
                currentArena = ArenaVenueId.LOCAL_PIT,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf("Capua Suburb Sand Crown"),
                notableVictories = mutableListOf("Decapitated Drusus the Novice in 12s"),
                notableDefeats = mutableListOf("Lost to Cassian during Capua festival"),
                knownWeaknesses = mutableListOf("Overextends aggressively on round opening"),
                recentForm = mutableListOf("W", "W", "W", "L", "W")
            ),
            PersistentFighter(
                id = "boss_wolf_secundus",
                name = "Secundus",
                nickname = "The Wolf",
                age = 21,
                origin = Origin.GREECE,
                ethnicity = "Illyrian Tribesman",
                gladiatorClass = GladiatorClass.THRAEX,
                ludusAffiliation = "Lanista Decimus",
                ownerName = "Decimus Pulcher",
                tier = OpponentTier.COMMON,
                aiPersonality = AiTacticalPersonality.BERSERKER,
                signatureTactic = "Wild Curved Flurry",
                equipmentSummary = "Curved sica & iron greaves",
                strength = 13,
                speed = 14,
                agility = 13,
                endurance = 12,
                reflex = 13,
                painTolerance = 13,
                swordsmanship = 11,
                shieldSkill = 10,
                discipline = 9,
                wins = 4,
                losses = 3,
                kills = 1,
                spared = 2,
                currentWinStreak = 1,
                prestige = 380,
                crowdApproval = 52,
                denariiEarned = 600,
                currentArena = ArenaVenueId.LOCAL_PIT,
                rankingPosition = 2,
                knownWeaknesses = mutableListOf("Easily baited into parry traps"),
                recentForm = mutableListOf("L", "W", "L", "W", "W"),
                isUnderground = true,
                undergroundBossState = BossState.ACTIVE
            ),
            PersistentFighter(
                id = "fighter_pit_2",
                name = "Servius",
                nickname = "The Boar",
                age = 29,
                origin = Origin.GERMANIA,
                ethnicity = "Suebi Tribesman",
                gladiatorClass = GladiatorClass.HEAVY_VETERAN,
                ludusAffiliation = "Independent Auctoratus",
                ownerName = "Self-Contracted",
                tier = OpponentTier.UNCOMMON,
                aiPersonality = AiTacticalPersonality.TANK,
                signatureTactic = "Unbending Stand",
                equipmentSummary = "Battered tower scutum & spatha",
                strength = 15,
                speed = 9,
                agility = 9,
                endurance = 16,
                reflex = 10,
                painTolerance = 18,
                swordsmanship = 12,
                shieldSkill = 15,
                discipline = 13,
                wins = 6,
                losses = 5,
                kills = 2,
                spared = 3,
                currentWinStreak = 0,
                prestige = 490,
                crowdApproval = 58,
                denariiEarned = 950,
                currentArena = ArenaVenueId.LOCAL_PIT,
                rankingPosition = 3,
                knownWeaknesses = mutableListOf("Sluggish lateral mobility"),
                recentForm = mutableListOf("L", "W", "W", "L", "L")
            ),

            // --- CAPUA ARENA ---
            PersistentFighter(
                id = "fighter_capua_champ",
                name = "Gaius",
                nickname = "The Bull",
                age = 28,
                origin = Origin.HISPANIA,
                ethnicity = "Celtiberian Veteran",
                gladiatorClass = GladiatorClass.MURMILLO,
                ludusAffiliation = "Domus Auctor",
                ownerName = "Lanista Decimus",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.AGGRESSOR,
                signatureTactic = "Goring Charge & Decisive Gladius Thrust",
                equipmentSummary = "Gilded Crested Helmet, Scutum with Bull Crest, Masterwork Gladius",
                strength = 18,
                speed = 13,
                agility = 12,
                endurance = 17,
                reflex = 14,
                painTolerance = 18,
                swordsmanship = 17,
                shieldSkill = 18,
                discipline = 16,
                wins = 18,
                losses = 5,
                kills = 7,
                spared = 2,
                currentWinStreak = 4,
                prestige = 3400,
                crowdApproval = 86,
                denariiEarned = 14200,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf("Capua Golden Laurel (Reigning)", "Campania Champion 68 A.U.C."),
                notableVictories = mutableListOf("Severed Spiculus' shield arm in 67 A.U.C.", "Vanquished 3 gladiators in single gauntlet"),
                notableDefeats = mutableListOf("Lost to Flamma in imperial exhibition in Rome"),
                knownWeaknesses = mutableListOf("Stamina depletes if fight extends beyond round 3"),
                knownInjuries = mutableListOf("Healed scar across right clavicle"),
                recentForm = mutableListOf("W", "W", "W", "W", "W")
            ),
            PersistentFighter(
                id = "fighter_cassian",
                name = "Cassian",
                nickname = "Blood Drinker",
                age = 26,
                origin = Origin.THRAX,
                ethnicity = "Thracian Noble Exile",
                gladiatorClass = GladiatorClass.THRAEX,
                ludusAffiliation = "Domus Auctor",
                ownerName = "Lanista Decimus",
                tier = OpponentTier.ELITE,
                aiPersonality = AiTacticalPersonality.DUELIST,
                signatureTactic = "Sica Hook around Scutum Rim",
                equipmentSummary = "Blackened Iron Sica, Bronze Parma, Winged Griffin Helm",
                strength = 15,
                speed = 17,
                agility = 16,
                endurance = 15,
                reflex = 17,
                painTolerance = 14,
                swordsmanship = 16,
                shieldSkill = 14,
                discipline = 15,
                wins = 12,
                losses = 3,
                kills = 4,
                spared = 1,
                currentWinStreak = 2,
                prestige = 2750,
                crowdApproval = 82,
                denariiEarned = 8800,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 2,
                notableVictories = mutableListOf("Humiliated Titus in Capua festival sandbox"),
                notableDefeats = mutableListOf("Lost to Gaius The Bull by split referee decision"),
                knownWeaknesses = mutableListOf("Vulnerable to heavy forward shield strikes"),
                recentForm = mutableListOf("W", "W", "L", "W", "W")
            ),
            PersistentFighter(
                id = "fighter_drusus",
                name = "Drusus",
                nickname = "Iron Wall",
                age = 31,
                origin = Origin.ITALIA,
                ethnicity = "Roman Auctoratus Veteran",
                gladiatorClass = GladiatorClass.MURMILLO,
                ludusAffiliation = "Ludus Popillius",
                ownerName = "Titus Popillius",
                tier = OpponentTier.ELITE,
                aiPersonality = AiTacticalPersonality.TANK,
                signatureTactic = "Unbreakable Testudo Posture",
                equipmentSummary = "Massive Bronze Scutum & Heavy Chain Greaves",
                strength = 16,
                speed = 10,
                agility = 10,
                endurance = 18,
                reflex = 12,
                painTolerance = 19,
                swordsmanship = 14,
                shieldSkill = 19,
                discipline = 18,
                wins = 11,
                losses = 7,
                kills = 2,
                spared = 5,
                currentWinStreak = 1,
                prestige = 2100,
                crowdApproval = 70,
                denariiEarned = 6200,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 3,
                knownWeaknesses = mutableListOf("Slow rotation; vulnerable to dual blade flanking"),
                recentForm = mutableListOf("W", "L", "W", "L", "W")
            ),
            PersistentFighter(
                id = "fighter_aulus",
                name = "Aulus",
                nickname = "The Shadow",
                age = 23,
                origin = Origin.GREECE,
                ethnicity = "Athenian Free Duelist",
                gladiatorClass = GladiatorClass.LIGHT_DUELIST,
                ludusAffiliation = "Ludus Gemini",
                ownerName = "Lucius Gemini",
                tier = OpponentTier.UNCOMMON,
                aiPersonality = AiTacticalPersonality.TRICKSTER,
                signatureTactic = "Blinding Sand Kick into Throat Riposte",
                equipmentSummary = "Duelist Gladius & Weighted Parrying Pugio",
                strength = 12,
                speed = 18,
                agility = 18,
                endurance = 13,
                reflex = 18,
                painTolerance = 11,
                swordsmanship = 15,
                shieldSkill = 8,
                discipline = 12,
                wins = 8,
                losses = 4,
                kills = 2,
                spared = 2,
                currentWinStreak = 2,
                prestige = 1800,
                crowdApproval = 76,
                denariiEarned = 4500,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 4,
                knownWeaknesses = mutableListOf("Low pain tolerance; one solid blow breaks rhythm"),
                recentForm = mutableListOf("W", "W", "L", "W", "L")
            ),

            // --- POMPEII ARENA ---
            PersistentFighter(
                id = "fighter_pompeii_champ",
                name = "Marcus",
                nickname = "The Serpent",
                age = 27,
                origin = Origin.NUMIDIA,
                ethnicity = "Numidian Prince Blood",
                gladiatorClass = GladiatorClass.RETIARIUS,
                ludusAffiliation = "Domus Aemilius",
                ownerName = "Lanista Aemilius",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.TRICKSTER,
                signatureTactic = "Double Net Ensnare & Throat Spear Puncture",
                equipmentSummary = "Silver-Weighted Net, Barbed Trident, Decorated Bronze Galerus",
                strength = 14,
                speed = 18,
                agility = 19,
                endurance = 16,
                reflex = 19,
                painTolerance = 14,
                swordsmanship = 16,
                shieldSkill = 11,
                discipline = 16,
                wins = 15,
                losses = 3,
                kills = 5,
                spared = 1,
                currentWinStreak = 5,
                prestige = 4600,
                crowdApproval = 89,
                denariiEarned = 21000,
                currentArena = ArenaVenueId.POMPEII,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf("Pompeii Trident Crown (Reigning)"),
                notableVictories = mutableListOf("Disarmed Secutor champion in 45 seconds"),
                notableDefeats = mutableListOf("Trapped by Gaius in corner at Capua Games"),
                knownWeaknesses = mutableListOf("If net is severed or blocked, loses 40% tactical range"),
                recentForm = mutableListOf("W", "W", "W", "W", "W")
            ),
            PersistentFighter(
                id = "fighter_felix",
                name = "Felix",
                nickname = "The Showman",
                age = 24,
                origin = Origin.ITALIA,
                ethnicity = "Roman Plebeian Idol",
                gladiatorClass = GladiatorClass.DIMACHAERUS,
                ludusAffiliation = "Domus Aemilius",
                ownerName = "Lanista Aemilius",
                tier = OpponentTier.ELITE,
                aiPersonality = AiTacticalPersonality.CROWD_PLAYER,
                signatureTactic = "Spinning Twin Slash to Wild Applause",
                equipmentSummary = "Matched Twin Damascus Steel Gladii",
                strength = 13,
                speed = 17,
                agility = 18,
                endurance = 14,
                reflex = 16,
                painTolerance = 12,
                swordsmanship = 17,
                shieldSkill = 6,
                discipline = 13,
                wins = 11,
                losses = 4,
                kills = 3,
                spared = 2,
                currentWinStreak = 2,
                prestige = 3400,
                crowdApproval = 92,
                denariiEarned = 13800,
                currentArena = ArenaVenueId.POMPEII,
                rankingPosition = 2,
                knownWeaknesses = mutableListOf("Prioritizes crowd spectacle over defense"),
                recentForm = mutableListOf("W", "L", "W", "W", "W")
            ),
            PersistentFighter(
                id = "fighter_dama",
                name = "Dama",
                nickname = "The Swift",
                age = 25,
                origin = Origin.SYRIA,
                ethnicity = "Syrian Spearman",
                gladiatorClass = GladiatorClass.HOPLOMACHUS,
                ludusAffiliation = "Domus Auctor",
                ownerName = "Lanista Decimus",
                tier = OpponentTier.UNCOMMON,
                aiPersonality = AiTacticalPersonality.DUELIST,
                signatureTactic = "Vaulting Spear Jab & Low Parma Guard",
                equipmentSummary = "Bronze Hasta, Short Dagger, Circular Steel Parma",
                strength = 13,
                speed = 18,
                agility = 17,
                endurance = 14,
                reflex = 17,
                painTolerance = 12,
                swordsmanship = 15,
                shieldSkill = 14,
                discipline = 15,
                wins = 9,
                losses = 4,
                kills = 2,
                spared = 2,
                currentWinStreak = 1,
                prestige = 2200,
                crowdApproval = 78,
                denariiEarned = 7200,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 5,
                knownWeaknesses = mutableListOf("Struggles against heavy net entanglement"),
                recentForm = mutableListOf("W", "W", "L", "W", "L")
            ),

            // --- NEAPOLIS ARENA ---
            PersistentFighter(
                id = "fighter_neapolis_champ",
                name = "Lysander",
                nickname = "The Lion",
                age = 29,
                origin = Origin.GREECE,
                ethnicity = "Spartan Bloodline",
                gladiatorClass = GladiatorClass.HOPLOMACHUS,
                ludusAffiliation = "Hellenic Gymnasium",
                ownerName = "Archon Theron",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.DUELIST,
                signatureTactic = "Phalanx Hasta Thrust & Round Shield Rim Bash",
                equipmentSummary = "Corinthian Plumed Helmet, Bronze Round Shield, Hasta Lance",
                strength = 16,
                speed = 16,
                agility = 15,
                endurance = 17,
                reflex = 16,
                painTolerance = 16,
                swordsmanship = 17,
                shieldSkill = 18,
                discipline = 18,
                wins = 16,
                losses = 2,
                kills = 6,
                spared = 1,
                currentWinStreak = 6,
                prestige = 6800,
                crowdApproval = 90,
                denariiEarned = 32000,
                currentArena = ArenaVenueId.NEAPOLIS,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf("Neapolis Hellenic Champion Laurel"),
                notableVictories = mutableListOf("Defeated Roman praetorian champion in exhibition"),
                notableDefeats = mutableListOf("Lost to Spiculus in Rome via disarm"),
                knownWeaknesses = mutableListOf("Rigid classical stance; struggles against chaotic unpredictable brawlers"),
                recentForm = mutableListOf("W", "W", "W", "W", "W")
            ),

            // --- ROME ARENA ---
            PersistentFighter(
                id = "fighter_rome_champ",
                name = "Spiculus",
                nickname = "The Invincible",
                age = 30,
                origin = Origin.GAUL,
                ethnicity = "Gallic Chieftain Blood",
                gladiatorClass = GladiatorClass.SECUTOR,
                ludusAffiliation = "Ludus Brutus",
                ownerName = "Lanista Brutus",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.VETERAN,
                signatureTactic = "Relentless Chaser Stride & Visor-Slit Decapitation",
                equipmentSummary = "Smooth Egg-Helm, Scutum with Imperial Eagle, Heavy Forged Blade",
                strength = 18,
                speed = 15,
                agility = 14,
                endurance = 19,
                reflex = 17,
                painTolerance = 19,
                swordsmanship = 19,
                shieldSkill = 19,
                discipline = 19,
                wins = 24,
                losses = 1,
                kills = 11,
                spared = 2,
                currentWinStreak = 9,
                prestige = 15000,
                crowdApproval = 95,
                denariiEarned = 78000,
                currentArena = ArenaVenueId.ROME,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf("Champion of the Circus Maximus", "Imperial Laurel 68 A.U.C."),
                notableVictories = mutableListOf("Only fighter to survive 4 consecutive imperial gauntlets"),
                notableDefeats = mutableListOf("Solo defeat against Flamma at the Colosseum inauguration"),
                knownWeaknesses = mutableListOf("Overly reliant on standard orthodox textbook patterns"),
                recentForm = mutableListOf("W", "W", "W", "W", "W")
            ),

            // --- COLOSSEUM LEGEND ---
            PersistentFighter(
                id = "fighter_colosseum_legend",
                name = "Flamma",
                nickname = "The Immortal",
                age = 34,
                origin = Origin.SYRIA,
                ethnicity = "Syrian Auxiliary Soldier",
                gladiatorClass = GladiatorClass.HEAVY_VETERAN,
                ludusAffiliation = "Ludus Imperialis",
                ownerName = "Imperial Treasury",
                tier = OpponentTier.LEGEND,
                aiPersonality = AiTacticalPersonality.BERSERKER,
                signatureTactic = "Refusal of Mercy & Blood Frenzy Whirler",
                equipmentSummary = "Gold-Embossed Segmentata, Spatha of Titus Caesar, Four-Times Rudis Wreath",
                strength = 20,
                speed = 15,
                agility = 14,
                endurance = 20,
                reflex = 18,
                painTolerance = 20,
                swordsmanship = 20,
                shieldSkill = 19,
                discipline = 20,
                wins = 34,
                losses = 4,
                kills = 21,
                spared = 4,
                currentWinStreak = 12,
                prestige = 28000,
                crowdApproval = 99,
                denariiEarned = 165000,
                currentArena = ArenaVenueId.COLOSSEUM,
                rankingPosition = 1,
                isChampion = true,
                championshipTitles = mutableListOf(
                    "Emperor's Golden Rudis (Refused 4 Times)",
                    "Colosseum Supreme Primus Palus",
                    "Undefeated God of the Arena"
                ),
                notableVictories = mutableListOf(
                    "Slew the Nemean Lion in venatio and 2 champions in same afternoon",
                    "Granted freedom 4 times by Emperor; chose to stay in the blood sands"
                ),
                notableDefeats = mutableListOf("4 honorable draws in youth against Roman praetorians"),
                knownWeaknesses = mutableListOf("Nearly none; blood frenzy can make him ignore own defense wounds"),
                recentForm = mutableListOf("W", "W", "W", "W", "W")
            ),
            PersistentFighter(
                id = "fighter_verus",
                name = "Verus",
                nickname = "The Titan",
                age = 32,
                origin = Origin.GERMANIA,
                ethnicity = "Germanic Colossus",
                gladiatorClass = GladiatorClass.SPECIAL_ARCHETYPE,
                ludusAffiliation = "Ludus Imperialis",
                ownerName = "Imperial Treasury",
                tier = OpponentTier.LEGEND,
                aiPersonality = AiTacticalPersonality.TANK,
                signatureTactic = "Twin Flail Skull Crusher",
                equipmentSummary = "Massive Bronze Spiked Buckler & Iron-Link Spiked Flail",
                strength = 19,
                speed = 13,
                agility = 12,
                endurance = 19,
                reflex = 15,
                painTolerance = 20,
                swordsmanship = 18,
                shieldSkill = 18,
                discipline = 18,
                wins = 28,
                losses = 6,
                kills = 15,
                spared = 5,
                currentWinStreak = 3,
                prestige = 22000,
                crowdApproval = 96,
                denariiEarned = 110000,
                currentArena = ArenaVenueId.COLOSSEUM,
                rankingPosition = 2,
                championshipTitles = mutableListOf("Colosseum Veteran Wreath"),
                recentForm = mutableListOf("W", "W", "W", "L", "W")
            ),
            // --- PERSISTENT UNDERGROUND BOSSES ---
            PersistentFighter(
                id = "boss_black_sand_aetius",
                name = "Aetius",
                nickname = "Black Sand",
                age = 28,
                origin = Origin.GAUL,
                ethnicity = "Gallic Brute",
                gladiatorClass = GladiatorClass.MURMILLO,
                ludusAffiliation = "Capua Quarry Gang",
                ownerName = "Centurion Varo",
                tier = OpponentTier.ELITE,
                aiPersonality = AiTacticalPersonality.TANK,
                signatureTactic = "Stone Crush Shield Bash",
                equipmentSummary = "Iron Tower Scutum & Segmentata",
                strength = 17,
                speed = 11,
                agility = 10,
                endurance = 18,
                reflex = 12,
                painTolerance = 18,
                swordsmanship = 15,
                shieldSkill = 16,
                discipline = 14,
                wins = 14,
                losses = 2,
                kills = 8,
                spared = 0,
                currentWinStreak = 6,
                prestige = 2400,
                crowdApproval = 75,
                denariiEarned = 5800,
                currentArena = ArenaVenueId.CAPUA,
                rankingPosition = 3,
                isUnderground = true,
                undergroundBossState = BossState.DORMANT
            ),
            PersistentFighter(
                id = "boss_syrian_tariq",
                name = "Tariq",
                nickname = "The Syrian",
                age = 26,
                origin = Origin.SYRIA,
                ethnicity = "Levantine Duelist",
                gladiatorClass = GladiatorClass.DIMACHAERUS,
                ludusAffiliation = "Neapolis Port Syndicate",
                ownerName = "Smuggler Barba",
                tier = OpponentTier.ELITE,
                aiPersonality = AiTacticalPersonality.DUELIST,
                signatureTactic = "Cross-Blade Flurry",
                equipmentSummary = "Dual Damascus Curved Daggers",
                strength = 14,
                speed = 18,
                agility = 17,
                endurance = 14,
                reflex = 18,
                painTolerance = 14,
                swordsmanship = 17,
                shieldSkill = 8,
                discipline = 15,
                wins = 16,
                losses = 3,
                kills = 9,
                spared = 1,
                currentWinStreak = 4,
                prestige = 3100,
                crowdApproval = 82,
                denariiEarned = 7200,
                currentArena = ArenaVenueId.NEAPOLIS,
                rankingPosition = 2,
                isUnderground = true,
                undergroundBossState = BossState.DORMANT
            ),
            PersistentFighter(
                id = "boss_gravedigger_maurus",
                name = "Maurus",
                nickname = "Gravedigger",
                age = 34,
                origin = Origin.NUMIDIA,
                ethnicity = "Numidian Veteran",
                gladiatorClass = GladiatorClass.HEAVY_VETERAN,
                ludusAffiliation = "Pompeii Crypt Cult",
                ownerName = "Sextus the Undertaker",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.BERSERKER,
                signatureTactic = "Bone Saw Cleave",
                equipmentSummary = "Notched Spatha & Heavy Bronze Greaves",
                strength = 18,
                speed = 12,
                agility = 11,
                endurance = 17,
                reflex = 13,
                painTolerance = 19,
                swordsmanship = 16,
                shieldSkill = 15,
                discipline = 13,
                wins = 21,
                losses = 5,
                kills = 14,
                spared = 0,
                currentWinStreak = 5,
                prestige = 4500,
                crowdApproval = 85,
                denariiEarned = 11000,
                currentArena = ArenaVenueId.POMPEII,
                rankingPosition = 1,
                isUnderground = true,
                undergroundBossState = BossState.DORMANT
            ),
            PersistentFighter(
                id = "boss_red_knife_servius",
                name = "Servius",
                nickname = "Red Knife",
                age = 24,
                origin = Origin.HISPANIA,
                ethnicity = "Iberian Outlaw",
                gladiatorClass = GladiatorClass.LIGHT_DUELIST,
                ludusAffiliation = "Rome Subura Brotherhood",
                ownerName = "Shadow Patrician",
                tier = OpponentTier.CHAMPION,
                aiPersonality = AiTacticalPersonality.TRICKSTER,
                signatureTactic = "Throat Dart Feint",
                equipmentSummary = "Iberian Falcata & Parrying Pugio",
                strength = 15,
                speed = 19,
                agility = 18,
                endurance = 15,
                reflex = 19,
                painTolerance = 15,
                swordsmanship = 18,
                shieldSkill = 12,
                discipline = 16,
                wins = 25,
                losses = 3,
                kills = 18,
                spared = 0,
                currentWinStreak = 8,
                prestige = 6200,
                crowdApproval = 90,
                denariiEarned = 18000,
                currentArena = ArenaVenueId.ROME,
                rankingPosition = 1,
                isUnderground = true,
                undergroundBossState = BossState.DORMANT
            )
        )
    }

    /**
     * Initial rivalries for the player's ludus.
     */
    fun createInitialRivalries(): MutableList<RivalryEntry> {
        return mutableListOf(
            RivalryEntry(
                opponentId = "fighter_cassian",
                opponentName = "Cassian",
                opponentNickname = "Blood Drinker",
                opponentLudus = "Domus Auctor",
                animosityScore = 85,
                animosityTitle = "Bitter Nemesis",
                boutsFought = 2,
                playerWins = 0,
                opponentWins = 2,
                reason = "Cassian brutally humiliated Titus in Capua local pit and insulted your dominus in public.",
                lastEncounterDateText = "Day -14 (Capua Festival)",
                rematchDemanded = true
            ),
            RivalryEntry(
                opponentId = "fighter_drusus",
                opponentName = "Drusus",
                opponentNickname = "Iron Wall",
                opponentLudus = "Ludus Popillius",
                animosityScore = 45,
                animosityTitle = "Honored Rival",
                boutsFought = 1,
                playerWins = 1,
                opponentWins = 0,
                reason = "Respectful clash at the Capua market games; Drusus seeks an honorable rematch to test his shield.",
                lastEncounterDateText = "Day -28 (Market Games)",
                rematchDemanded = false
            )
        )
    }

    /**
     * Generate procedural gladiator to ensure absolute zero duplicate fatigue.
     */
    fun generateProceduralOpponent(tier: OpponentTier, venue: ArenaVenueId, day: Int): PersistentFighter {
        val firstNames = listOf(
            "Crixus", "Oenomaus", "Castus", "Gannicus", "Vettius", "Maximus", "Spartacus",
            "Atticus", "Bato", "Marcellus", "Decius", "Varus", "Aurelius", "Tiberius",
            "Faustus", "Valens", "Drusus", "Calpurnius", "Agrippa", "Servilius", "Brutus"
        )
        val nicknames = listOf(
            "The Viper", "Iron Fist", "Bonebreaker", "The Ghost", "Silver Fang", "Thunder",
            "The Scythe", "Red Wolf", "Sand Fox", "The Butcher", "Gorgon", "Hammer of Gaul",
            "The Unbroken", "Stormbringer", "The Jackal", "Shadow Blade", "Nine Lives"
        )
        val ethnicOrigins = listOf(
            Pair(Origin.THRAX, "Thracian Warrior"),
            Pair(Origin.GAUL, "Gallic Berserker"),
            Pair(Origin.GERMANIA, "Germanic Chieftain"),
            Pair(Origin.HISPANIA, "Iberian Swordsman"),
            Pair(Origin.NUMIDIA, "Numidian Skirmisher"),
            Pair(Origin.GREECE, "Spartan Freedman"),
            Pair(Origin.SYRIA, "Syrian Archer & Duelist"),
            Pair(Origin.ITALIA, "Disgraced Centurion")
        )
        val ludusNames = listOf(
            "Domus Auctor", "Domus Aemilius", "Ludus Brutus", "Ludus Popillius",
            "Capua Sand Guild", "Neapolis Hellenic Gym", "Etruria Lanistae", "Imperial Pit"
        )

        val name = firstNames.random()
        val nick = nicknames.random()
        val originPair = ethnicOrigins.random()
        val gladiatorClass = GladiatorClass.values().random()
        val personality = AiTacticalPersonality.values().random()

        val statBase = when (tier) {
            OpponentTier.COMMON -> 10 to 13
            OpponentTier.UNCOMMON -> 12 to 15
            OpponentTier.ELITE -> 14 to 17
            OpponentTier.CHAMPION -> 16 to 19
            OpponentTier.LEGEND -> 18 to 20
        }

        fun stat(): Int = Random.nextInt(statBase.first, statBase.second + 1)

        val winsBase = when (tier) {
            OpponentTier.COMMON -> Random.nextInt(1, 5)
            OpponentTier.UNCOMMON -> Random.nextInt(5, 10)
            OpponentTier.ELITE -> Random.nextInt(10, 16)
            OpponentTier.CHAMPION -> Random.nextInt(15, 22)
            OpponentTier.LEGEND -> Random.nextInt(25, 40)
        }
        val lossesBase = Random.nextInt(1, 6)

        return PersistentFighter(
            id = "fighter_gen_${day}_${Random.nextInt(1000, 9999)}",
            name = name,
            nickname = nick,
            age = Random.nextInt(20, 32),
            origin = originPair.first,
            ethnicity = originPair.second,
            gladiatorClass = gladiatorClass,
            ludusAffiliation = ludusNames.random(),
            ownerName = "Lanista ${firstNames.random()}",
            tier = tier,
            aiPersonality = personality,
            signatureTactic = "Signature ${gladiatorClass.primaryWeapon} assault",
            equipmentSummary = "${gladiatorClass.primaryWeapon} & ${gladiatorClass.secondaryWeapon}",
            strength = stat(),
            speed = stat(),
            agility = stat(),
            endurance = stat(),
            reflex = stat(),
            painTolerance = stat(),
            swordsmanship = stat(),
            shieldSkill = stat(),
            discipline = stat(),
            wins = winsBase,
            losses = lossesBase,
            kills = (winsBase * 0.35f).toInt(),
            spared = (lossesBase * 0.40f).toInt(),
            currentWinStreak = Random.nextInt(0, 4),
            prestige = venue.minPrestige + Random.nextInt(100, 800),
            crowdApproval = Random.nextInt(55, 90),
            denariiEarned = winsBase * 500,
            currentArena = venue,
            rankingPosition = Random.nextInt(2, 10),
            recentForm = mutableListOf("W", "W", "L", "W", "W")
        )
    }

    /**
     * Creates an initial 14-day calendar schedule with matches for the circuit.
     */
    fun createInitialCalendar(
        currentDay: Int,
        fighters: List<PersistentFighter>
    ): MutableList<ArenaCalendarBout> {
        val bouts = mutableListOf<ArenaCalendarBout>()
        val capuaFighters = fighters.filter { it.currentArena == ArenaVenueId.CAPUA || it.currentArena == ArenaVenueId.LOCAL_PIT }

        // Day 1 to 14
        for (day in 1..14) {
            val f1 = capuaFighters.randomOrNull() ?: fighters.first()
            val f2 = capuaFighters.filter { it.id != f1.id }.randomOrNull() ?: fighters.last()
            val isPlayerDay = (day == 3 || day == 7 || day == 11)

            val matchType = when (day) {
                7 -> ArenaMatchType.CHAMPIONSHIP_MATCH
                3 -> ArenaMatchType.RIVALRY_MATCH
                else -> listOf(ArenaMatchType.STANDARD_DUEL, ArenaMatchType.EXHIBITION, ArenaMatchType.BEAST_HUNT).random()
            }

            bouts.add(
                ArenaCalendarBout(
                    id = "bout_day_$day",
                    day = day,
                    venueId = f1.currentArena,
                    fighter1Id = f1.id,
                    fighter1Name = f1.fullDisplayName,
                    fighter1Ludus = f1.ludusAffiliation,
                    fighter2Id = if (isPlayerDay) "player" else f2.id,
                    fighter2Name = if (isPlayerDay) "Titus (Your Ludus)" else f2.fullDisplayName,
                    fighter2Ludus = if (isPlayerDay) "Ludus Tuus" else f2.ludusAffiliation,
                    matchType = matchType,
                    isPlayerMatch = isPlayerDay
                )
            )
        }
        return bouts
    }
}
